site_name: Paweł Jankiewicz
site_url: https://pjankiewicz.github.io/blog
author: Paweł Jankiewicz
description: "Blog about programming, AI, Machine Learning"
posts_dir: posts_md
posts_output_dir: posts
templates_dir: templates
static_dir: static
output_dir: .